### ISSUE TITLE
There seems to be a bug somewhere

### ISSUE THREAD

**Issue by fdddzddd** [Rubiksman78/MonikA.I#104]
Everytime I try to message Monika, it stays loading for around 10 seconds, then she tells me "There seems to be a bug somewhere". In my terminal, this appears:
Launch failed. Please check if text-generation_webui is running.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\main.py", line 248, in listenToClient
    page = launch(context)
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\main.py", line 128, in launch
    page.wait_for_load_state("networkidle")
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\sync_api\_generated.py", line 9421, in wait_for_load_state
    self._sync(self._impl_obj.wait_for_load_state(state=state, timeout=timeout))
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\_impl\_page.py", line 491, in wait_for_load_state
    return await self._main_frame.wait_for_load_state(**locals_to_params(locals()))
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\_impl\_frame.py", line 237, in wait_for_load_state
    return await self._wait_for_load_state_impl(state, timeout)
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\_impl\_frame.py", line 265, in _wait_for_load_state_impl
    await waiter.result()
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\main.py", line 254, in listenToClient
    pw.stop()
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\sync_api\_context_manager.py", line 90, in __exit__
    self._connection.stop_sync()
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\_impl\_connection.py", line 283, in stop_sync
    self.cleanup()
  File "C:\Users\guyth\OneDrive\Documents\MAS\MonikAI_v20\libs\lib\site-packages\playwright\_impl\_connection.py", line 299, in cleanup
    callback.future.set_exception(self._closed_error)
asyncio.exceptions.InvalidStateError: invalid state

Also, I use a GTX 1650 with the model Airoboros L2 13B Gpt4 M2.0

**Comment by Sylphar** [comment]
Did you try to click update.bat beforehand ? Does your "login screen" (after you press run.bat) has a pink and white background ? If no, things didn't update properly, and I recommend downloading the main.py file here on this github and replacing the one you have.

**Comment by fdddzddd** [comment]
Everytime I press update.bat, it shows me the following:
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Requirement already satisfied: PyYAML in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: numpy in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 2)) (1.26.3)
Requirement already satisfied: playwright in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 3)) (1.40.0)
Requirement already satisfied: torch in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 4)) (2.5.1+cu121)
Requirement already satisfied: torchvision in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 5)) (0.20.1+cu121)
Requirement already satisfied: torchaudio in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 6)) (2.5.1+cu121)
Requirement already satisfied: ipython in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 7)) (8.18.0)
Requirement already satisfied: greenlet==3.0.1 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from playwright->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: pyee==11.0.1 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from playwright->-r requirements.txt (line 3)) (11.0.1)
Requirement already satisfied: typing-extensions in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from pyee==11.0.1->playwright->-r requirements.txt (line 3)) (4.12.2)
Requirement already satisfied: filelock in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (3.13.1)
Requirement already satisfied: networkx in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (3.1.3)
Requirement already satisfied: fsspec in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (2024.2.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from sympy==1.13.1->torch->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torchvision->-r requirements.txt (line 5)) (10.2.0)
Requirement already satisfied: decorator in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (3.0.41)
Requirement already satisfied: pygments>=2.4.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (2.17.2)
Requirement already satisfied: stack-data in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.6.3)
Requirement already satisfied: traitlets>=5 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (5.13.0)
Requirement already satisfied: exceptiongroup in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (1.2.0)
Requirement already satisfied: colorama in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from jedi>=0.16->ipython->-r requirements.txt (line 7)) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->-r requirements.txt (line 7)) (0.2.12)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from jinja2->torch->-r requirements.txt (line 4)) (2.1.5)
Requirement already satisfied: executing>=1.2.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from stack-data->ipython->-r requirements.txt (line 7)) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from stack-data->ipython->-r requirements.txt (line 7)) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from stack-data->ipython->-r requirements.txt (line 7)) (0.2.2)
Requirement already satisfied: six>=1.12.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from asttokens>=2.1.0->stack-data->ipython->-r requirements.txt (line 7)) (1.16.0)

[process exited with code 0 (0x00000000)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

And even after I replaced my main.py, the "login screen still has a gray background, like shown in the screenshot below
![image](https://github.com/user-attachments/assets/ee017e0e-a6e2-4c6a-bf07-cdb28910eae7)

**Comment by Sylphar** [comment]
You can try manually downloading every "script" from the script folder on this github repo and replacing your existing folder with this one. Afterwards, with both the changes in scripts and the main, the problem should be solved

**Comment by Rubiksman78** [comment]
Please also check that you correctly downloaded the last zip from the Google Drive link as it should be a git repository, your `update.bat` script doesn't run as intended because the folder is not recognized as a git which can pull updates from here.

**Comment by fdddzddd** [comment]
I replaced the script files, turned the file into a git repository, but now, when I try try to run the update script, it gives me this:
remote: Enumerating objects: 1540, done.
remote: Counting objects: 100% (256/256), done.
remote: Compressing objects: 100% (170/170), done.
error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
error: 2270 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Requirement already satisfied: PyYAML in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: numpy in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 2)) (1.26.3)
Requirement already satisfied: playwright in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 3)) (1.40.0)
Requirement already satisfied: torch in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 4)) (2.5.1+cu121)
Requirement already satisfied: torchvision in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 5)) (0.20.1+cu121)
Requirement already satisfied: torchaudio in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 6)) (2.5.1+cu121)
Requirement already satisfied: ipython in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from -r requirements.txt (line 7)) (8.18.0)
Requirement already satisfied: greenlet==3.0.1 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from playwright->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: pyee==11.0.1 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from playwright->-r requirements.txt (line 3)) (11.0.1)
Requirement already satisfied: typing-extensions in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from pyee==11.0.1->playwright->-r requirements.txt (line 3)) (4.12.2)
Requirement already satisfied: filelock in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (3.13.1)
Requirement already satisfied: networkx in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (3.1.3)
Requirement already satisfied: fsspec in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (2024.2.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torch->-r requirements.txt (line 4)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from sympy==1.13.1->torch->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from torchvision->-r requirements.txt (line 5)) (10.2.0)
Requirement already satisfied: decorator in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (3.0.41)
Requirement already satisfied: pygments>=2.4.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (2.17.2)
Requirement already satisfied: stack-data in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.6.3)
Requirement already satisfied: traitlets>=5 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (5.13.0)
Requirement already satisfied: exceptiongroup in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (1.2.0)
Requirement already satisfied: colorama in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from ipython->-r requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from jedi>=0.16->ipython->-r requirements.txt (line 7)) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->-r requirements.txt (line 7)) (0.2.12)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from jinja2->torch->-r requirements.txt (line 4)) (2.1.5)
Requirement already satisfied: executing>=1.2.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from stack-data->ipython->-r requirements.txt (line 7)) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from stack-data->ipython->-r requirements.txt (line 7)) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from stack-data->ipython->-r requirements.txt (line 7)) (0.2.2)
Requirement already satisfied: six>=1.12.0 in c:\users\guyth\onedrive\documents\mas\monikai_v20\libs\lib\site-packages (from asttokens>=2.1.0->stack-data->ipython->-r requirements.txt (line 7)) (1.16.0)

[process exited with code 0 (0x00000000)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

**Comment by Rubiksman78** [comment]
I would advise making the installation from scratch correctly by downloading the zip file from the drive and just run the updater inside it again.

**Comment by fdddzddd** [comment]
I did. Pretty much everything works now. I just need to fix some things with the text web ui. Thank you both so much for your help
