### ISSUE TITLE
Enable cookie imports from web browser

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Rubiksman78/MonikA.I#22]
Self explanatory. Based on my Reddit thread that got downvoted to hell. Users who signed up for the service using their Goofy account won’t be able to use this, as there is no password, and you cannot change the password. A solution is to allow the user to import cookies from their web browser then forward them to use the already signed in user.

**Comment by Rubiksman78** [comment]
Thank you for your suggestion. As I explained I won't do it myself as it is already possible to create another account quite simply. Feel free to do a PR if you want to add this feature.
