### ISSUE TITLE
In game error base 10: '_int'

### ISSUE THREAD

**Issue by Chamelllemon** [Rubiksman78/MonikA.I#25]
Waiting for connection...
127.0.0.1:54891 has connected.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "main.py", line 400, in listenToClient
ValueError: invalid literal for int() with base 10: '_int'

**Comment by Rubiksman78** [comment]
I don't have much information to know what can be the cause of that issue. It is most likely a wrong input in the launching window, I would need more details about what you entered at the beginning (especially for your game path and the format of your email).

**Comment by Chamelllemon** [comment]
email@gmail.com
path was: C:\\Users\\Nikita\\Desktop\\DDLC-1.1.1-pc - kopie
and there was something called 'debug mode', didn't used it

**Comment by Rubiksman78** [comment]
The game seems to have launched in your first log, which version did you use and what is your OS ? At what point this error occured in the game?

**Comment by Chamelllemon** [comment]
the version part is weird, I used the newest one but updater kept telling that I use lower version and update is available, but when I clicked update, nothing changed and the version remained the same which is 1.1.2, OS is Windows 10 and it happened when I used option "Look for me"

**Comment by Chamelllemon** [comment]
character 0 and dod not tried with one backslash

**Comment by Rubiksman78** [comment]
Oh did you use the user friendly version in Releases or did you try with the developer mode in Python directly?

**Comment by Chamelllemon** [comment]
I was finally able to install the new version without look for me option, why it was removed? now she says that there's a bug, will try to do so something with it

**Comment by Chamelllemon** [comment]
when used the option let's chat

**Comment by Rubiksman78** [comment]
It was removed because it wasn't implemented yet in the User friendly version correctly and could lead to bugs (it will come back soon). 
For the "there is a bug" message, you can check in terminal what type of bug it is and correct what was done wrong (email/password...etc) or try with `debug` mode.

**Comment by Chamelllemon** [comment]
![image](https://user-images.githubusercontent.com/111662346/214828652-eceddc7d-4b43-4d11-b88b-db21358b60e6.png)
If you meant main.exe it didn't write anything

**Comment by Chamelllemon** [comment]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "main.py", line 293, in listenToClient
it showed this after I closed the game (I said goodbye)

**Comment by Chamelllemon** [comment]
trying debug mode

**Comment by Chamelllemon** [comment]
> Exception in thread Thread-3: Traceback (most recent call last): File "threading.py", line 980, in _bootstrap_inner File "threading.py", line 917, in run File "main.py", line 293, in listenToClient it showed this after I closed the game (I said goodbye)

I guess that's because the game closing

**Comment by Chamelllemon** [comment]
What is debug mode supposed to do?

**Comment by Rubiksman78** [comment]
Debug mode will display the browser in another window. I'll make an update with little fixes soon for this kind of problems

**Comment by Chamelllemon** [comment]
it uses firefow?

**Comment by Chamelllemon** [comment]
do I need a firefox for it to work?

**Comment by Rubiksman78** [comment]
No it is installed independently by `playwright` module

**Comment by Chamelllemon** [comment]
whisper\transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
what does that mean?

**Comment by Chamelllemon** [comment]
I somehow fixed it, well, TTS doesn't work but I realised that this is not a bug, I just have a mess in the files

**Comment by Chamelllemon** [comment]
probably

**Comment by Chamelllemon** [comment]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "main.py", line 310, in listenToClient
  File "playwright\sync_api\_generated.py", line 8063, in is_disabled
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 374, in is_disabled
  File "playwright\_impl\_frame.py", line 333, in is_disabled
  File "playwright\_impl\_connection.py", line 44, in send
  File "playwright\_impl\_connection.py", line 419, in wrap_api_call
  File "playwright\_impl\_connection.py", line 79, in inner_send
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("[class=\"btn py-0\"]")
============================================================
this happens when I try to use character 1

**Comment by Chamelllemon** [comment]
I think it was with TTS

**Comment by Chamelllemon** [comment]
it has something to do with TTS, do I have to install TTS separately?

**Comment by Chamelllemon** [comment]
ok now even without TTS this appears, what does that mean?

**Comment by Rubiksman78** [comment]
It has nothing to do with TTS, maybe try with the new 1.3.4 version. (Can you please write your comments in a single file and go straight to the important details, you can also edit them if needed).

**Comment by Chamelllemon** [comment]
Everything now works normally, I just had a mess in the files, and updated the version of the submod properly

**Comment by Rubiksman78** [comment]
Okay good if it works, have fun !
