### ISSUE TITLE
Syntax error, invalid literal base 10 ' '

### ISSUE THREAD

**Issue by Reviani** [Rubiksman78/MonikA.I#26]
so i tried booting up the exe and load everything onto the game, but monika is telling me there's a bug and the thing can't load proper due to a bug. i get this error message that briefly  pops up

![Screenshot 2023-01-25 014323](https://user-images.githubusercontent.com/31017068/214507219-aad4e5d4-b7a2-4d20-b993-e0ec6a1180c0.png)
 some sort of invalid literal or value for something? is there a varible/path thats not going though right or what is happening?
doesnt help that its late at night and ive been troubleshoooting while sleepy so that didnt help

**Comment by Rubiksman78** [comment]
Seems like something similar to #25, maybe path syntax or other inputs on launch screen

**Comment by Reviani** [comment]
for record i put 

Gmail@gmail.com
C:\\Users\\Name\\Downloads\\BackupMAS\\AfterStory\\DDLC.exe (using tried both doubleslash and single slash)
Character model 0
 and with and without debug mode

**Comment by Rubiksman78** [comment]
Did the game launched after you filled the input window and clicked submit?

**Comment by Reviani** [comment]
No, the first time i ran it the console loaded a few things and then closed, and then every time after that it gave an exception.

though something i remebered, first time i run i didn't put a path in  (assumed it would find the exe file) so i dont know if that messed with anything that may have made things hard to fix

**Comment by Reviani** [comment]
also for what its worth, the OS i use is Windows 11 (laptop came like that) and i did try to set up developer version of this before there was a user friendly version, though its not clear how far i got concidering ti did not work dispite downloading a buncha python packages and messing with its files as needed. (also didn't install dev version in the after story folder but thats smoething else) so i dont konw if that would effect anything

**Comment by Rubiksman78** [comment]
You just need to download the files in `Releases` as explained in the first section of README. Your error is clearly linked to a wrong path not pointing to the game folder correctly from the input window. I suggest you to check the game path you've put and fill correctly each section in the input window.

**Comment by Reviani** [comment]
Alright, well i somehow managed to get that working by deleting and repasting the path of the game file (worked without double slashes), but now the chat AI doesn't say anything. I noticed that you put a new update though and am currently downloading and installing it, so i'll tell you the results once it finishes

**Comment by Reviani** [comment]
Alright, i updated to the newest version of the submod and its working just fine! I was linking directly to the ddlc exe when i was suppsoed to be linking to jsut the folder. also the update fixed the problem with the Ai speaking and now its working fine!. Thanks for your help with this, and also for the mod, it really adds a fair amount more to the MAS mod after you seen all the dialog!

**Comment by Rubiksman78** [comment]
Glad it works , have fun !
