### ISSUE TITLE
Keeps saying "Oh sorry (user), it seems there is a bug somewhere. I will try to fix it as soon as possible"

### ISSUE THREAD

**Issue by m4syum4r0** [Rubiksman78/MonikA.I#34]

**Comment by Rubiksman78** [comment]
Can you please give details about:
- What version you used for the submod
- What happens when you use the Debug mode
- If there are error messages displayed in the terminal

**Comment by HedgiePlay** [comment]
im getting the same error too i'm using 1.4.1 of the MonikA.I and my MAS version is 0.12.13

**Comment by Rubiksman78** [comment]
And as for the 2 other points?

**Comment by HedgiePlay** [comment]
there was no error in the Terminal and i still doesn't work when i use debug mode

**Comment by cenkjan21** [comment]
That happens to me too can you tell me if its something about affection

**Comment by Rubiksman78** [comment]
> there was no error in the Terminal and i still doesn't work when i use debug mode

What happens with debug mode on ? Normally a new window should open with a browser when you send a chat message.
If it does, please describe what is happening and if it gets stucked somewhere.
If not, there might something done wrong in the installation and I would suggest to read carefully the wiki page.

**Comment by Rubiksman78** [comment]
> That happens to me too can you tell me if its something about affection

It has nothing to do with affection, I haven't made a lower bound to use the features of my submod.

**Comment by popdanceytb** [comment]
> > there was no error in the Terminal and i still doesn't work when i use debug mode
> 
> What happens with debug mode on ? Normally a new window should open with a browser when you send a chat message. If it does, please describe what is happening and if it gets stucked somewhere. If not, there might something done wrong in the installation and I would suggest to read carefully the wiki page.

same, i checked if playwright was installed, and when i use the chatbot ai ( yes option) with debug mode it opens a tab but it asks to put login informations, around 5 seconds after the tab opens with the login page it closes and monika says that a bug is somewhere.

**Comment by Rubiksman78** [comment]
> same, i checked if playwright was installed, and when i use the chatbot ai ( yes option) with debug mode it opens a tab but it asks to put login informations, around 5 seconds after the tab opens with the login page it closes and monika says that a bug is somewhere.

If the login page opened and nothing was filled automatically, you either didn't put your IDs for CAI on the submod login screen when running `run.bat` or you didn't create correctly a CAI account. Please do these before trying to use the feature.

**Comment by popdanceytb** [comment]
> 

I put the login infos correctly and checked for it multiple times. I should look at my CAI account maybe the issue hides somewhere in my account.
