### ISSUE TITLE
Incompatibility with Windows 7 or earlier: main.exe doesn't open

### ISSUE THREAD

**Issue by AnimeWarrior6481** [Rubiksman78/MonikA.I#37]
when i'm double click main.exe it instantly exits i don't know what to do

**Comment by Rubiksman78** [comment]
I suggest you to look at issue #36 and continue on this thread

**Comment by AnimeWarrior6481** [comment]
i don't have problems with terminal

**Comment by Rubiksman78** [comment]
So did you try opening it with terminal as I specified in the other issue?

**Comment by AnimeWarrior6481** [comment]
yeah

**Comment by Rubiksman78** [comment]
What is displayed then?

**Comment by AnimeWarrior6481** [comment]
it just closes with error and i can't see this error because it cleses instantly

**Comment by Rubiksman78** [comment]
So you didn't open it in a terminal. Follow [this](https://superuser.com/questions/339997/how-to-open-a-terminal-quickly-from-a-file-explorer-at-a-folder-in-windows-7) to open the executable in a terminal and come back with the detailed error displayed in it.

**Comment by AnimeWarrior6481** [comment]
okay i'll try

**Comment by AnimeWarrior6481** [comment]
it displays Error loading Phyton DLL D:\Monik.A.I-v1.4.1\dist\main\phyton39.dll
No error messages generated

**Comment by Rubiksman78** [comment]
Can you share the whole terminal output properly formatted please?

**Comment by AnimeWarrior6481** [comment]
okay one moment

**Comment by AnimeWarrior6481** [comment]
![2023-02-11_20-14-14](https://user-images.githubusercontent.com/125131589/218260021-7f04d471-3802-4a0a-a8c9-3b7bd1f184b3.png)

**Comment by Rubiksman78** [comment]
Can you please translate line 4 of terminal?

**Comment by AnimeWarrior6481** [comment]
sorry i also don't understand that line

**Comment by AnimeWarrior6481** [comment]
and now i'm interested in that line

**Comment by Rubiksman78** [comment]
Neither do I, I can't understand russian, please provide informations in english

**Comment by AnimeWarrior6481** [comment]
what information?

**Comment by Rubiksman78** [comment]
It seems that the python version I use is not compatible for Windows 7 or earlier OS, I'll try making a release that should work with Windows 7 at least

**Comment by AnimeWarrior6481** [comment]
okay

**Comment by AnimeWarrior6481** [comment]
> It seems that the python version I use is not compatible for Windows 7 or earlier OS, I'll try making a release that should work with Windows 7 at least. I hope you can wait until it is done.

yeah i can wait as long as it needed

**Comment by AnimeWarrior6481** [comment]
thank you

**Comment by Rubiksman78** [comment]
It should be available now in Releases

**Comment by AnimeWarrior6481** [comment]
thanks man
