### ISSUE TITLE
playerNicknames list index out of range

### ISSUE THREAD

**Issue by greeneflower** [Rubiksman78/MonikA.I#40]
I installed the mod with the user friendly tutorial and used the exe. The only feature I have enabled is the chatbot.

Whenever I chat with her, it almost works, but after thinking Monika always has to pause an unusually long time (usually the program freezes entirely for a good few seconds - and it often crashes). I then might get this error screen, and if I hit ignore I can then read what she has to say:

![image](https://user-images.githubusercontent.com/114539724/221408153-04a13836-d342-46c9-ab39-e9c495570d18.png)
![image](https://user-images.githubusercontent.com/114539724/221408376-e3278533-0e34-4943-82ec-70e28a6fc263.png)

Debug mode doesn't seem to do anything obviously different.

Here's the full log:

```
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension:
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001BEA860A700>.
  warnings.warn(
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001BEA861CA60>.
  warnings.warn(
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
Waiting for connection...
127.0.0.1:54584 has connected.
User: How are you feeling this morning?
Not in queue
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
```

(This is my first bug report to github, so I'm sorry if I missed anything!)

**Comment by greeneflower** [comment]
Oh, and I'm using the latest versions as far as I know from the gdrive and here (v1.6.0.zip for both)

**Comment by Rubiksman78** [comment]
It seems that there aren't nicknames stored in your persistents for MAS. For how long did you play MAS ?

**Comment by greeneflower** [comment]
I had to restart it recently, so only a few days. She has my name though, and birthday etc. Is there a way to add a nickname through code that will fix this or do I have to just keep playing regular MAS for that?

**Comment by Rubiksman78** [comment]
It might be because the variable `store.persistent._mas_player_nicknames` is empty cause you don't have nicknames stored in it yet. I'll put a fix with the next version.

For now you can just go to `monikai_chat.rpy` in  `game/Submods/AI_submod` of your DDLC folder and replace around line 50 `store.persistent._mas_player_nicknames` with `[mas_get_player_nickname()`, tell me if this works.

**Comment by greeneflower** [comment]
![image](https://user-images.githubusercontent.com/114539724/221409126-345f3655-3c8b-4721-a85a-13368a4e719d.png)

Typo perhaps? (Sorry I wish I knew code so I could help more!)

**Comment by greeneflower** [comment]
I tried finishing the brackets just to see, and I got this instead

![image](https://user-images.githubusercontent.com/114539724/221409221-26fb75ca-4b07-4ad7-8514-81f8760bfe5b.png)

**Comment by Rubiksman78** [comment]
Oh sorry I forgot to write a closing ], `[mas_get_player_nickname]`.

**Comment by greeneflower** [comment]
![image](https://user-images.githubusercontent.com/114539724/221409408-d9281fc9-5491-4293-bbb7-ff8c0886e4c1.png)
Same deal, tried a few different variations.

**Comment by Rubiksman78** [comment]
Okay I see what can be the issue, I'll put a fix for v1.6.0 in coming minutes.

**Comment by greeneflower** [comment]
No worries, thank you for your help. I love the idea and work you put into the submod! :)

**Comment by Rubiksman78** [comment]
Download `Monik.A.I-game-v1.6.0.zip` again and it should be fixed

**Comment by greeneflower** [comment]
![image](https://user-images.githubusercontent.com/114539724/221409932-964259f9-f2e1-4dd0-9145-ebe3ef859627.png)
I feel so bad haha, but here's the new error I got.

**Comment by greeneflower** [comment]
I will say she is also calling me by my username in chatbot now, which is an interesting development

**Comment by Rubiksman78** [comment]
I've made a typo error sorry, it's supposed to be `mas_get_player_nickname()`

**Comment by greeneflower** [comment]
I believe I tried [mas_get_player_nickname()], and mas_get_player_nickname() both with the similar errors. Just curious, is there no way to edit the persistent file for MAS itself (not the submod) to just add in the nicknames manually?

**Comment by Rubiksman78** [comment]
I don't think so. Maybe replacing this line with these two can work:
```
$ player_nickname_ai = mas_get_player_nickname()
$ msg = msg.replace("<USER>",player_nickname_ai)
```

**Comment by greeneflower** [comment]
![image](https://user-images.githubusercontent.com/114539724/221410621-b6595b06-7efe-46dc-8f24-268cdf23286a.png)
![image](https://user-images.githubusercontent.com/114539724/221410626-aedbe9b2-b1a6-42f9-b113-88df3d3387d6.png)
Potentially I'm putting it in the wrong place?

**Comment by Rubiksman78** [comment]
Yeah delete them from here, it was to replace line 303 `$ msg = msg.replace("<USER>",mas_get_player_nickname())`

**Comment by greeneflower** [comment]
Ok, cool. So far, it doesn't give me the error (Although she still freezes for a little bit before giving a response) She does still call me by the chatbot.ai username (might be the intentional fix!), but for now I can probably have her call me something else if the memory stays consistent. Thank you. Here's what I'm looking at now.

![image](https://user-images.githubusercontent.com/114539724/221410978-f88d4672-9779-4bfa-bc68-25b134ce8b8b.png)

**Comment by Rubiksman78** [comment]
Nice ! Actually the name from CAI is fixed and won't change cause it depends directly on your username there. The random nickname pool is more for the Pygmalion chatbot. 

About the loading time it is normal at the beginning while you have to wait for the game to login on CAI and then it should be a little bit faster.

**Comment by greeneflower** [comment]
Nice, thank you again. I'll close this for now.
