### ISSUE TITLE
cudart64_110.dll not found (v1.6.1)

### ISSUE THREAD

**Issue by AnimeWarrior6481** [Rubiksman78/MonikA.I#42]
uh hello it's me again i'm sorry to bother you but i have another problem on the new version
i'm going to attach a image of my error and again i'm sorry to bother you
i don't know maybe i just have a bad pc
![2023-02-26_21-51-16](https://user-images.githubusercontent.com/125131589/221422000-f9f88a94-ed35-43d2-9561-d88fce27fd5f.png)

**Comment by Rubiksman78** [comment]
It seems like an error with GPU configuration, you might want to follow the setup of CUDA [here](https://github.com/Rubiksman78/MonikA.I/wiki/Install-Pygmalion-locally). Did you use the old TTS or the new one?

**Comment by AnimeWarrior6481** [comment]
i don't know which tts i use i just download a new version and delete old version

**Comment by AnimeWarrior6481** [comment]
i'm sorry i don't really that much in programming and this stuff

**Comment by Rubiksman78** [comment]
What options did you choose on the login screen?

**Comment by AnimeWarrior6481** [comment]
on that login screen?

**Comment by Rubiksman78** [comment]
Nevermind it was an import error that doesn't matter, you can try following the guide in my first reponse and I'll try to make a release without GPU.

**Comment by AnimeWarrior6481** [comment]
okay

**Comment by AnimeWarrior6481** [comment]
Okay so I read install Pygmalion locally and I think that it needs an Nvidia gpu right?

**Comment by Rubiksman78** [comment]
Yes, the specs are specified there

**Comment by AnimeWarrior6481** [comment]
Well I don't have an Nvidia so it may be a trouble for me

**Comment by Rubiksman78** [comment]
Okay I'll make a build available asap

**Comment by AnimeWarrior6481** [comment]
What is asap?

**Comment by Rubiksman78** [comment]
As soon as possible

**Comment by AnimeWarrior6481** [comment]
Okay I'll wait then

**Comment by Rubiksman78** [comment]
I've made a new built and a new procedure to have separate setup for CPU or GPU. Check the new tutorial here: https://github.com/Rubiksman78/MonikA.I/wiki/Installation-tutorial-(after-1.6.1)

**Comment by AnimeWarrior6481** [comment]
i installed all as it says in the new tutorial

**Comment by Rubiksman78** [comment]
Can you launch the file `run.bat` from your terminal?

Do `right click` in the project folder in a blank space, click `Open in terminal/Command Prompt`, when the terminal open write `./run.bat`, enter and do the login. Then report the error that will be displayed.

**Comment by Rubiksman78** [comment]
There were some issue with this new procedure, check the wiki again and follow the new instructions.

**Comment by AnimeWarrior6481** [comment]
okay i'll try to follow the instructions and tell you the result

**Comment by AnimeWarrior6481** [comment]
when i try to install a c++ build tools but it displays error so i can't install c++ build tools

**Comment by Rubiksman78** [comment]
What is the error? I suggest you to follow the tutorial linked and find the version of Visual Studio that corresponds to your OS.

**Comment by Rubiksman78** [comment]
I've updated the wiki page and the new drive link. You can maybe try with this new install.

**Comment by AnimeWarrior6481** [comment]
Okay I'll try

**Comment by AnimeWarrior6481** [comment]
great now i have this problem
![2023-02-28_19-52-46](https://user-images.githubusercontent.com/125131589/221859574-25ddb860-3ac9-4410-b005-b5d1d4189453.png)
i'm already tired of getting this errors
maybe i need a new pc

**Comment by AnimeWarrior6481** [comment]
yes i download a new file and follow all the instruction except a setup a gpu

**Comment by Rubiksman78** [comment]
I've updated it quiet recently, maybe you can check again. Can you show me your folder after unzipping it please?

**Comment by AnimeWarrior6481** [comment]
that folder?

**Comment by AnimeWarrior6481** [comment]
where i unzip this right?

**Comment by Rubiksman78** [comment]
Yes the `Monik.A.I-v1.6.1.zip` folder after extracting it

**Comment by AnimeWarrior6481** [comment]
this folder?
![2023-02-28_20-43-47](https://user-images.githubusercontent.com/125131589/221872114-45022d7b-25bd-418b-92be-225e56bb4198.png)
or this folder?
![2023-02-28_20-44-27](https://user-images.githubusercontent.com/125131589/221872196-560d007b-2064-4b38-9bcd-5cd43709ef2b.png)

**Comment by Rubiksman78** [comment]
Try running `update.bat` and then running `run.bat`. If it still doesn't work, reinstall the zip file from the link that might have been updated from before.

**Comment by AnimeWarrior6481** [comment]
when i first download a new zip file for first i run run.bat then i run update.bat
but okay i'll try to reinstall zip file

**Comment by Rubiksman78** [comment]
This error was due to a forgotten package on my side. I'll update the zip file asap, sorry for the inconvenience.

**Comment by Rubiksman78** [comment]
It is updated, let me know if you run into other errors.

**Comment by AnimeWarrior6481** [comment]
i download an updated version
then i run update.bat
then i run run.bat and now it shows this
![2023-03-01_16-31-27](https://user-images.githubusercontent.com/125131589/222099826-cf4538ae-c96f-403c-8937-a6b3c41c94d9.png)

**Comment by AnimeWarrior6481** [comment]
does this mean that i already have this requrirement?

**Comment by Rubiksman78** [comment]
Yes, there were some bugs with the actual link, I'll update it once again with the messing packages.

**Comment by AnimeWarrior6481** [comment]
okay i'll wait

**Comment by Rubiksman78** [comment]
Here: https://drive.google.com/file/d/12If6hb7HvoYkLYzuh52wAWLn6KOQ6f6m/view?usp=sharing

**Comment by AnimeWarrior6481** [comment]
okay thanks

**Comment by AnimeWarrior6481** [comment]
i download this new version and it displays the same as my last screenshot

**Comment by AnimeWarrior6481** [comment]
thanks the login screen has appear

**Comment by AnimeWarrior6481** [comment]
so i need just to fill the options and submit and then the game will be turned on right?

**Comment by Rubiksman78** [comment]
Yes, follow the wiki.

**Comment by AnimeWarrior6481** [comment]
okay thanks for the help

**Comment by Rubiksman78** [comment]
I'll close this issue for now. Feel free to reopen it if you run into other troubles not addressed in the documentation.
