### ISSUE TITLE
Cant get executables to open. Only Run

### ISSUE THREAD

**Issue by BumBumForFun** [Rubiksman78/MonikA.I#47]

**Comment by Rubiksman78** [comment]
Please provide more details about the issue and the steps to reproduce it with the proper tracebacks.

**Comment by BumBumForFun** [comment]
I would open Run and try to get Main to open but it keeps closing immediately. Even when using the command prompt or powershell

**Comment by Rubiksman78** [comment]
If you open it correctly through a command prompt or powershell it shouldn't close. I need the error to provide correct support.

**Comment by BumBumForFun** [comment]
fixed now

**Comment by Rubiksman78** [comment]
Good I'll close this for now
