### ISSUE TITLE
i need help can you guys give me full steps what to do 

### ISSUE THREAD

**Issue by cenkjan21** [Rubiksman78/MonikA.I#48]
i tried everything but it just says i am sorry theres a bug maybe i didsomething wrong downloading i didnt understand the tutorial can you guys give me full steps on downloading

**Comment by Rubiksman78** [comment]
Please describe in details and provide information about:
- which version you've downloaded
- what options you've chosen from the login screen after launching `run.bat`
- any other behaviours you have noticed

**Comment by Rubiksman78** [comment]
I will close it for now, feel free to reopen it.
