### ISSUE TITLE
pip's dependency resolver does not currently take into account all the packages that are installed

### ISSUE THREAD

**Issue by Sidowskyy** [Rubiksman78/MonikA.I#52]
so sorry to bother but I've tried my best to install this submod. Whenever I run setup I come across this eroor
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tts 0.11.1 requires inflect==5.6.0, but you have inflect 6.0.2 which is incompatible.
tts 0.11.1 requires librosa==0.8.0, but you have librosa 0.8.1 which is incompatible.
tts 0.11.1 requires numba==0.55.1; python_version < "3.10", but you have numba 0.56.4 which is incompatible.
tts 0.11.1 requires numpy==1.21.6; python_version < "3.10", but you have numpy 1.24.2 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.

I've tried running update and run but it ended in a same result. 

Overall it dosen't crash the game. Just says in game that there's a bug somewhere

should I just delete everything submod related and start over ?

**Comment by Rubiksman78** [comment]
This error is not important if you did the other steps of installation correctly, don't pay attention to it.
