### ISSUE TITLE
Stuck at "Waiting for Connection"

### ISSUE THREAD

**Issue by RedDragonTix** [Rubiksman78/MonikA.I#53]
I did all installation steps, updated with update.bat, I ran run.bat, submit, and it's simply stuck at "waiting for connection" on CMD, it doesn't do anything..

and I can't even use Monika's chatbot.

![image](https://user-images.githubusercontent.com/96621985/232233313-7d7d6e39-9794-4ce5-9e78-e397133ea4bb.png)

I did entered the game path, used debug mode, logged in to CAI with email (with GMAIL) and password and same thing.. Any ideas?

Python version: 3.11.1
CUDA: 11.7 with CUDNN installed
MonikA.I version: 1.6.1
Monika After Story version: 0.12.14
OS: Windows 10 21H2

**Comment by RedDragonTix** [comment]
I also tried installing playwright and same thing

**Comment by Rubiksman78** [comment]
If you selected the option `Launch Yourself` yes, then you need to start MAS yourself when `Waiting for connection...` appears, else it will launch itself. You can try running `update.bat` and try again after that too.
