### ISSUE TITLE
Unable to launch Main.py or Voicing.py on Mac

### ISSUE THREAD

**Issue by kaue5480** [Rubiksman78/MonikA.I#54]
**Describe the bug**
Main.py says it is missing TTS.utils and Voicing.py is unable to find IPython after everything has been downloaded as told in the wiki

**To Reproduce**
Steps to reproduce the behavior (Both):
1. Go to 'MonikA.I'
2. Click on 'Main.py' or 'Voicing.py'
**Expected behavior(Main.py)**
Unknown as it would not open
**Expected behavior(Voicing.py)**
Monika would be voiced
**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] 1.6.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaue5480** [comment]
Another thing please make the install process be a bit more explained as I could not tell if I should something or not

**Comment by Rubiksman78** [comment]
DId you download the `sourcecode.zip` or did you clone the repository (better option). 
To install TTS libs, did you clone the concerned repository as indicated on the Wiki and install them as instructed?
Be careful also to use the `requirements.txt` for MacOS as there are some tricky modules for it.

**Comment by kaue5480** [comment]
I downloaded the 'sourcecode.zip' and did use 'requirements_macos.txt` and downloaded tortise-TTS

**Comment by Rubiksman78** [comment]
Try launching one of the two scripts from within a command prompt to get the exact error traceback and submit it here.

**Comment by kaue5480** [comment]
Below is main.py
<img width="564" alt="Screenshot 2023-04-16 at 9 41 54 AM" src="https://user-images.githubusercontent.com/130204090/232315368-6c560f33-814b-4c97-9bf2-97dcbbcdb178.png">
Below is Voicing.py
<img width="566" alt="Screenshot 2023-04-16 at 9 42 53 AM" src="https://user-images.githubusercontent.com/130204090/232315410-74e20104-3ad8-4b96-86a7-bf45fe2da942.png">

**Comment by Rubiksman78** [comment]
Did you clone the repository TTS and run `pip install -e .` inside it without errors? Can you also run the command `pip list` and send the list of the modules installed?

**Comment by kaue5480** [comment]
I cloned both TTS's and here is the pip list
<img width="403" alt="Screenshot 2023-04-16 at 10 18 20 AM" src="https://user-images.githubusercontent.com/130204090/232319234-25b41e87-c714-4291-8abc-9ebb51d3aaa0.png">

**Comment by kaue5480** [comment]
<img width="1440" alt="Screenshot 2023-04-16 at 10 19 25 AM" src="https://user-images.githubusercontent.com/130204090/232319303-1f0bc56a-18c9-4111-bf4e-957572d8dc99.png">
Here is a pip list not restricted by folder

**Comment by Rubiksman78** [comment]
TTS is not present, be sure to have not messed up with which python you are using and which pip is linked to it. To avoid errors, you can use `python -m pip` or `py -m pip` to install modules relatively to the python you are using.

**Comment by kaue5480** [comment]
Alright thanks for the help

**Comment by kaue5480** [comment]
I have tried doing the python3 -m pip which did nothing but brought up the pip commands

**Comment by Rubiksman78** [comment]
Your installation of modules is broken, document yourself on how to install libraries on python with the right python you are using. In your case, it was not linked to another python which is not the one used by your PC by default.
