### ISSUE TITLE
Installing CUDA not required?

### ISSUE THREAD

**Issue by iceypotato** [Rubiksman78/MonikA.I#59]
So I saw that I had to install CUDA 11.7 and the cudnn libraries for this program to use the GPU to generate text. However, I saw that the GPU was being utilized when generating the responses (about 100% utilization), without the CUDA Tookit and cudnn libraries. So, is CUDA still needed, or did I do something wrong?

**Comment by Rubiksman78** [comment]
You need to setup CUDA and cudnn if you want to use heavy GPU features like locally running chatbots or Tortoise TTS. If these are not setup, these features won't use your GPU and will use your CPU, resulting in slower processing.

Be careful to distinguish your integrated GPU (Intel for example) and your dedicated GPU if you have one (only Nvidia GPU are supported for the libraries used).

**Comment by Rubiksman78** [comment]
What options are you using? Is it the local chatbot or CAI ?

**Comment by Rubiksman78** [comment]
What is the time response approximatively ? Quantified by seconds and words would be good

**Comment by Rubiksman78** [comment]
I was talking about the amount of words generated by the model but anyway 14 seconds seems not too long to me. Which model did you use?
