### ISSUE TITLE
WARNING: Ignoring invalid distribution -yping-extensions (e:\monika.i\libs\pythonlib\lib\site-packages)

### ISSUE THREAD

**Issue by pro0gaming** [Rubiksman78/MonikA.I#61]
Every time I try setup it says WARNING: Ignoring invalid distribution -yping-extensions (e:\monika.i\libs\pythonlib\lib\site-packages)
Despite that, I finished everything, but when I open the game, Monca says that there are bugs somewhere

**Comment by Rubiksman78** [comment]
This warning is not important, if you have an error, try running `update.bat` and try again.
