### ISSUE TITLE
tortoise_models.zip wont download

### ISSUE THREAD

**Issue by Jurycze** [Rubiksman78/MonikA.I#62]
Well i have a big problem becouse every time i download about 80-90% it says "connection error"
this is where i download it: https://drive.google.com/file/d/1yAoG1cl5gEwa1thcTi-Mwma5AIaWCQxN/view
and i have an idea that if someone have the file please upload it on MEGA and send me link on discord (jura GD#6768)
thanks for help and have a nice day

**Comment by Rubiksman78** [comment]
Be sure to indeed have a stable wifi connection while downloading these files.
