### ISSUE TITLE
CAI bug

### ISSUE THREAD

**Issue by DeathW1ng39** [Rubiksman78/MonikA.I#63]
So basically if you try to open CAI for the first time, now there is a mobile app promotion that messes up the code (since you can't click anywhere while it's on the screen). And so for that reason there would be the exact same error every time you try to speak to the bot. 
![изображение](https://github.com/Rubiksman78/MonikA.I/assets/124525666/6093a1f1-b09b-42e0-a657-c6e1ab6cd3d7)

I've tried to work around this issue just by clicking fast enough, but for some reason after I actually closed the promotion manually, it took me to Sing Up page instead of Log in.

**Comment by Anzuki17g** [comment]
Same happens to me, cannot find any fix. We should wait for an update, I guess.

**Comment by DeathW1ng39** [comment]
UPD: So perhaps it's an only me issue, but after I fixed the code to go for Login instead of Signing in, no data was inputted into the email & password spaces, and it kept closing. I'll try to fix it further, though. (The promotion still needs to be closed manually, since in I couldn't find the "class" to close it automatically)

**Comment by Rubiksman78** [comment]
The promotion page is indeed made to be closed manually as explained in the wiki. As for the login thing, it'd need more investigation as it was working one week ago, maybe another change in the CAI frontend.

**Comment by DeathW1ng39** [comment]
Yeah, I see it now, but for some reason in mine main.py it was set to "btn btn-primary btn-sm", instead of needed "btn btn-secondary btn-sm" (even though I don't remember modifying it).

I just tested it with replacing code from this main.py to mine (from the line 219 "def first_start(context):" to the line 240 "return page") and it worked (I did close the promotion on my own and everything past this point worked as intended). Yet it still printed("Not in queue"). 

After testing without debug mode, the aforementioned print command still worked, and I got the same "Not in queue" message, even though I got the response. So, the main issue was solved for the moment.

**Comment by Rubiksman78** [comment]
The "Not in queue" message is intended and just indicates if you have been queued on the website (it can happen when it is too crowded). As for the previous fix, it'd need some tests on my side to confirmate.

**Comment by DeathW1ng39** [comment]
Okay, so it works so far, but the messages seem to cut out as if there was a character limit. 
![изображение](https://github.com/Rubiksman78/MonikA.I/assets/124525666/7936b359-a919-46c4-b071-fdaedbede29f)
So this is what I get 
![изображение](https://github.com/Rubiksman78/MonikA.I/assets/124525666/97fb2cbc-dd10-48be-a288-b44d7182f9c8)
And here are the full messages.

**Comment by Rubiksman78** [comment]
Yes there is indeed a recent modification on the CAI website that made it difficult with the code to know when to end the parsing of the text, I still haven't figured out a way to fix this.
