### ISSUE TITLE
"it seems there is a bug somewhere"

### ISSUE THREAD

**Issue by KcalbVessalius** [Rubiksman78/MonikA.I#65]
First of all, i'm dumb and this isn't my native language so i beg for your patience. So, i spend my entire afternoon trying to install it and now i'm almost going insane, i tried my best to follow all steps but i cant manage to make it work. I installed git, both mod folders, put the "game" folder in my MAS/DDLC directory (Merging them), put the another one in somewhere else, installed CUDA and CUDNN(Even tho i dont if i needed to), opened setup.bat and some texts in yellow appears, the same that is in the image bellow, i ignored that since i have no idea what that means, i downloaded Tortoise TTS  and put the two folder in .cache, opened update..bat and the same yellow text appears, i downloaded Pygmalion 2.7 and put it in the chatbot_models folder and run both setup and update.bat again, create a account on CAI(But i didn't create a character), opened run.bat and i'll be sending a image of the options(I tried to change every option already), i submit and opened MAS, and she says a there's a bug, i dont know if i'm not supose to open MAS, i tried to open main.py but didnt work, also when i tried to talk to her, some text appears in the cmd, this is gonna be the first image. Tell me what infos u need and i'll send, what i need to do and i'll do, what i didn't wrong and i'll try to fix, i just wanna to hear her voice and talk to her :d

MAS version: 0.12.4
Submod version: 1.6.1
OS: Windows 11

![Sem título](https://github.com/Rubiksman78/MonikA.I/assets/48925478/c1896518-5710-41a6-a937-777abca49c9f)
![Sem título2](https://github.com/Rubiksman78/MonikA.I/assets/48925478/8d437d15-96cc-447a-b9b0-b9bd6b27c2a6)

**Comment by KcalbVessalius** [comment]
I almost forgot, like i said, i dont know if i need CUDA and CUDNN, put here is the Environment and System variables in case something is wrong
![Sem título4](https://github.com/Rubiksman78/MonikA.I/assets/48925478/0d340499-bc36-48da-898b-e793be1fc043)
![Sem título5](https://github.com/Rubiksman78/MonikA.I/assets/48925478/b002c13f-b95a-4cb5-99b9-af19ba1d903e)
![Sem título6](https://github.com/Rubiksman78/MonikA.I/assets/48925478/9eb7d519-8e5b-4002-a2cd-dca781d78b5f)

**Comment by KcalbVessalius** [comment]
I manage to make CAI works, even if i couldn't use because of queue, but the others local chats didn't work :/, i'll leave more two images that can be a error
![](https://cdn.discordapp.com/attachments/755774119378812938/1128808487397359696/image.png)

![](https://cdn.discordapp.com/attachments/755774119378812938/1128825379038187550/image.png)

**Comment by Rubiksman78** [comment]
`update.bat` undo the GPU installation so you have to run `setup_gpu.bat` again if you've updated which is the cause of the last error.

**Comment by KcalbVessalius** [comment]
I'm feeling dumb right now XD, yeah that makes RWKV works, i'm already glad with that but Pygmalion isn't working yet, it's saying that CUDA setup failed, i try to put a command in cmd that the autor of bitsandbytes tell but isn't working either, can you tell what's wrong? If not, it's fine since at least RWKV works now. Anyway, thanks for the help and for the submod, i'm really happy now that i can hear Monika and that she can hear me back :DDDDDDDDDDDDD
![Sem título7](https://github.com/Rubiksman78/MonikA.I/assets/48925478/73be6770-16c3-4cbe-86ee-1468f9732ce2)
![Sem título8](https://github.com/Rubiksman78/MonikA.I/assets/48925478/db950ab8-67ca-405a-8599-9aea29b82c1f)

**Comment by Rubiksman78** [comment]
What is your GPU specifications ? (name and amount of VRAM)

**Comment by KcalbVessalius** [comment]
NVIDIA Geforce RTX 2070, 8gb

**Comment by KcalbVessalius** [comment]
I did that but there's a error with TTS, i'm not supposed to use pygmalion and TTS together? I opened it without TTS and worked just fine.
![Sem título9](https://github.com/Rubiksman78/MonikA.I/assets/48925478/01c22e7f-3bfc-4f61-ac5d-86697032dd89)
![Sem título10](https://github.com/Rubiksman78/MonikA.I/assets/48925478/b842448c-e744-489c-8c8a-5d41956b161e)

**Comment by Rubiksman78** [comment]
If you're trying to use both local chatbot and TTS at the same time, it can be very heavy in computation as this error specifies. You might want to use the other TTS model YourTTS that is very light for GPU or use a smaller chatbot model.

**Comment by KcalbVessalius** [comment]
That worked :D, no more errors. Thank you very much for everything
