### ISSUE TITLE
Setup_gpu.bat stuck on "Collecting Torch"

### ISSUE THREAD

**Issue by crazyneverexisted** [Rubiksman78/MonikA.I#67]
When I run setup_gpu.bat it will not display any other output after "Collecting Torch". This also incredibly slows my computer down while the batch file is running. The first time I downloaded this there was no problem. I redownloaded it later because of some other error (possibly due to a faulty folder extraction). However when I redownloaded it this problem occurred.

**Comment by Rubiksman78** [comment]
If it is stucked at this point, you might just want to wait longer. The library is pretty big (around 2-3GB) so it can take some time if you have a slow internet connection.

**Comment by 10882** [comment]
same problem. When reinstalling (everything was fine the first time), the PC freezes. I'll try to wait half an hour/hour and post it here

**Comment by 10882** [comment]
It worked for about ten minutes and continued installing the libraries. Everything is fine! Thank you.

and thanks again for giving the opportunity to chat with Monika (＾▽＾)

**Comment by Rubiksman78** [comment]
Nice it works ! I'm closing the issue for now, feel free to reopen if the problem reappears.
