### ISSUE TITLE
"Torch not Compiled with CUDA enabled" error when running with a pygmalion chat bot.

### ISSUE THREAD

**Issue by crazyneverexisted** [Rubiksman78/MonikA.I#69]
When I use a chat bot model it shows this error.

**Comment by Rubiksman78** [comment]
Please provide more details about your GPU specifications and what model you are trying to use.

**Comment by crazyneverexisted** [comment]
I am

**Comment by Rubiksman78** [comment]
AMD GPUs are not compatible with the modules used for AI in Python unfortunately. You can try using your CPU only or use CAI.

**Comment by crazyneverexisted** [comment]
How would I use cpu?

**Comment by Rubiksman78** [comment]
Just don't run the `setup_gpu.bat` file, but it is clearly not advised as the response time will be very slow on CPU.
