### ISSUE TITLE
Monika keeps repeating herself.

### ISSUE THREAD

**Issue by KitLoaf1** [Rubiksman78/MonikA.I#75]
Monika keeps repeating herself.

![02-09-_2023_20-06-28](https://github.com/Rubiksman78/MonikA.I/assets/103464561/9179dab8-a203-4c4e-8d9e-8b5bb5fbd975)
![02-09-_2023_20-06-49](https://github.com/Rubiksman78/MonikA.I/assets/103464561/faae1fec-bc4c-487d-a382-62903668c2ad)

**Comment by Rubiksman78** [comment]
This should be fixed with 1.6.2, please download the latest zip or just run update.bat.

**Comment by KitLoaf1** [comment]
This showed up after I ran update.bat. Any Ideas how to fix this?

**Comment by Rubiksman78** [comment]
Please show the terminal output when you ran update.bat, maybe a wrong update.

**Comment by KitLoaf1** [comment]
HEAD is now at d5e0f55 Merge pull request #70 from Rubiksman78/dev
Der Befehl "rm" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Collecting git+https://github.com/openai/whisper.git (from -r requirements.txt (line 9))
  Cloning https://github.com/openai/whisper.git to c:\users\grafik\appdata\local\temp\pip-req-build-9bh7l9kg
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git 'C:\Users\GRAFIK\AppData\Local\Temp\pip-req-build-9bh7l9kg'
  Resolved https://github.com/openai/whisper.git to commit e8622f9afc4eba139bf796c210f5c01081000472
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting playwright~=1.31.0
  Using cached playwright-1.31.1-py3-none-win_amd64.whl (28.8 MB)
Collecting IPython~=8.10.0
  Using cached ipython-8.10.0-py3-none-any.whl (784 kB)
Collecting tensorflow~=2.11.0
  Using cached tensorflow-2.11.1-cp38-cp38-win_amd64.whl (1.9 kB)
Collecting opencv-python~=4.7.0.72
  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
Collecting transformers~=4.26.1
  Using cached transformers-4.26.1-py3-none-any.whl (6.3 MB)
Collecting Pillow~=9.4.0
  Using cached Pillow-9.4.0-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting SpeechRecognition~=3.9.0
  Using cached SpeechRecognition-3.9.0-py2.py3-none-any.whl (32.8 MB)
Collecting tk~=0.1.0
  Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting bitsandbytes~=0.37.0
  Using cached bitsandbytes-0.37.2-py3-none-any.whl (84.2 MB)
Collecting numpy==1.23.0
  Using cached numpy-1.23.0-cp38-cp38-win_amd64.whl (14.7 MB)
Collecting PyAudio
  Using cached PyAudio-0.2.13-cp38-cp38-win_amd64.whl (164 kB)
Collecting pyee==9.0.4
  Using cached pyee-9.0.4-py2.py3-none-any.whl (14 kB)
Collecting greenlet==2.0.1
  Using cached greenlet-2.0.1-cp38-cp38-win_amd64.whl (190 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting stack-data
  Using cached stack_data-0.6.2-py3-none-any.whl (24 kB)
Collecting matplotlib-inline
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting jedi>=0.16
  Using cached jedi-0.19.0-py2.py3-none-any.whl (1.6 MB)
Collecting pygments>=2.4.0
  Using cached Pygments-2.16.1-py3-none-any.whl (1.2 MB)
Collecting prompt-toolkit<3.1.0,>=3.0.30
  Using cached prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
Collecting traitlets>=5
  Using cached traitlets-5.9.0-py3-none-any.whl (117 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting tensorflow-intel==2.11.1
  Using cached tensorflow_intel-2.11.1-cp38-cp38-win_amd64.whl (266.3 MB)
Collecting h5py>=2.9.0
  Using cached h5py-3.9.0-cp38-cp38-win_amd64.whl (2.7 MB)
Collecting six>=1.12.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting grpcio<2.0,>=1.24.3
  Using cached grpcio-1.57.0-cp38-cp38-win_amd64.whl (4.3 MB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp38-cp38-win_amd64.whl (1.5 MB)
Collecting gast<=0.4.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting wrapt>=1.11.0
  Using cached wrapt-1.15.0-cp38-cp38-win_amd64.whl (36 kB)
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting keras<2.12,>=2.11.0
  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
Collecting protobuf<3.20,>=3.9.2
  Using cached protobuf-3.19.6-cp38-cp38-win_amd64.whl (896 kB)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting packaging
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting setuptools
  Using cached setuptools-68.1.2-py3-none-any.whl (805 kB)
Collecting tensorflow-estimator<2.12,>=2.11.0
  Using cached tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)
Collecting tensorboard<2.12,>=2.11
  Using cached tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
Collecting libclang>=13.0.0
  Using cached libclang-16.0.6-py2.py3-none-win_amd64.whl (24.4 MB)
Collecting flatbuffers>=2.0
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting absl-py>=1.0.0
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting termcolor>=1.1.0
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting filelock
  Using cached filelock-3.12.3-py3-none-any.whl (11 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0.1-cp38-cp38-win_amd64.whl (157 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting huggingface-hub<1.0,>=0.11.0
  Using cached huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
Collecting regex!=2019.12.17
  Using cached regex-2023.8.8-cp38-cp38-win_amd64.whl (268 kB)
Collecting tqdm>=4.27
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Using cached tokenizers-0.13.3-cp38-cp38-win_amd64.whl (3.5 MB)
Collecting more-itertools
  Using cached more_itertools-10.1.0-py3-none-any.whl (55 kB)
Collecting torch
  Using cached torch-2.0.1-cp38-cp38-win_amd64.whl (172.4 MB)
Collecting numba
  Using cached numba-0.57.1-cp38-cp38-win_amd64.whl (2.6 MB)
Collecting tiktoken==0.3.3
  Using cached tiktoken-0.3.3-cp38-cp38-win_amd64.whl (579 kB)
Collecting fsspec
  Using cached fsspec-2023.9.0-py3-none-any.whl (173 kB)
Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.2.0-cp38-cp38-win_amd64.whl (96 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Collecting llvmlite<0.41,>=0.40.0dev0
  Using cached llvmlite-0.40.1-cp38-cp38-win_amd64.whl (27.7 MB)
Collecting importlib-metadata
  Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.3.0-py2.py3-none-any.whl (27 kB)
Collecting executing>=1.2.0
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting wheel<1.0,>=0.23.0
  Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting werkzeug>=1.0.1
  Using cached werkzeug-2.3.7-py3-none-any.whl (242 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.4-py3-none-any.whl (94 kB)
Collecting zipp>=0.5
  Using cached zipp-3.16.2-py3-none-any.whl (7.2 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp38-cp38-win_amd64.whl (17 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.6.0,>=0.4.6
  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Building wheels for collected packages: openai-whisper
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20230314-py3-none-any.whl size=807707 sha256=e703388861c3c4b6074d56a6ce185fb9c699eeb7e7ce0590caeda500ad4a8319
  Stored in directory: C:\Users\GRAFIK\AppData\Local\Temp\pip-ephem-wheel-cache-pbs88z3n\wheels\a7\70\18\b7693c07b1d18b3dafb328f5d0496aa0d41a9c09ef332fd8e6
Successfully built openai-whisper
Installing collected packages: wcwidth, tokenizers, tk, tensorboard-plugin-wit, PyAudio, pure-eval, pickleshare, mpmath, libclang, flatbuffers, executing, bitsandbytes, backcall, zipp, wrapt, wheel, urllib3, typing-extensions, traitlets, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, sympy, six, setuptools, regex, pyyaml, pygments, pyasn1, protobuf, prompt-toolkit, Pillow, parso, packaging, oauthlib, numpy, networkx, more-itertools, MarkupSafe, llvmlite, keras, idna, grpcio, greenlet, gast, fsspec, decorator, colorama, charset-normalizer, certifi, cachetools, absl-py, werkzeug, tqdm, rsa, requests, pyee, pyasn1-modules, opt-einsum, opencv-python, matplotlib-inline, jinja2, jedi, importlib-metadata, h5py, google-pasta, filelock, astunparse, asttokens, torch, tiktoken, stack-data, SpeechRecognition, requests-oauthlib, playwright, numba, markdown, huggingface-hub, google-auth, transformers, openai-whisper, IPython, google-auth-oauthlib, tensorboard, tensorflow-intel, tensorflow
  Attempting uninstall: wcwidth
    Found existing installation: wcwidth 0.2.6
    Uninstalling wcwidth-0.2.6:
      Successfully uninstalled wcwidth-0.2.6
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.13.3
    Uninstalling tokenizers-0.13.3:
      Successfully uninstalled tokenizers-0.13.3
  Attempting uninstall: tk
    Found existing installation: tk 0.1.0
    Uninstalling tk-0.1.0:
      Successfully uninstalled tk-0.1.0
  Attempting uninstall: tensorboard-plugin-wit
    Found existing installation: tensorboard-plugin-wit 1.8.1
    Uninstalling tensorboard-plugin-wit-1.8.1:
      Successfully uninstalled tensorboard-plugin-wit-1.8.1
  Attempting uninstall: PyAudio
    Found existing installation: PyAudio 0.2.13
    Uninstalling PyAudio-0.2.13:
      Successfully uninstalled PyAudio-0.2.13
  Attempting uninstall: pure-eval
    Found existing installation: pure-eval 0.2.2
    Uninstalling pure-eval-0.2.2:
      Successfully uninstalled pure-eval-0.2.2
  Attempting uninstall: pickleshare
    Found existing installation: pickleshare 0.7.5
    Uninstalling pickleshare-0.7.5:
      Successfully uninstalled pickleshare-0.7.5
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: libclang
    Found existing installation: libclang 16.0.6
    Uninstalling libclang-16.0.6:
      Successfully uninstalled libclang-16.0.6
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 23.5.26
    Uninstalling flatbuffers-23.5.26:
      Successfully uninstalled flatbuffers-23.5.26
  Attempting uninstall: executing
    Found existing installation: executing 1.2.0
    Uninstalling executing-1.2.0:
      Successfully uninstalled executing-1.2.0
  Attempting uninstall: bitsandbytes
    Found existing installation: bitsandbytes 0.37.2
    Uninstalling bitsandbytes-0.37.2:
      Successfully uninstalled bitsandbytes-0.37.2
  Attempting uninstall: backcall
    Found existing installation: backcall 0.2.0
    Uninstalling backcall-0.2.0:
      Successfully uninstalled backcall-0.2.0
  Attempting uninstall: zipp
    Found existing installation: zipp 3.16.2
    Uninstalling zipp-3.16.2:
      Successfully uninstalled zipp-3.16.2
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.15.0
    Uninstalling wrapt-1.15.0:
      Successfully uninstalled wrapt-1.15.0
  Attempting uninstall: wheel
    Found existing installation: wheel 0.41.2
    Uninstalling wheel-0.41.2:
      Successfully uninstalled wheel-0.41.2
  WARNING: The script wheel.exe is installed in 'C:\Users\GRAFIK\OneDrive - Stadt Wil Informatik-Dienste Schulen Wil\Desktop\MonikA.I\libs\pythonlib\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.16
    Uninstalling urllib3-1.26.16:
      Successfully uninstalled urllib3-1.26.16
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: traitlets
    Found existing installation: traitlets 5.9.0
    Uninstalling traitlets-5.9.0:
      Successfully uninstalled traitlets-5.9.0
  Attempting uninstall: termcolor
    Found existing installation: termcolor 2.3.0
    Uninstalling termcolor-2.3.0:
      Successfully uninstalled termcolor-2.3.0
  Attempting uninstall: tensorflow-io-gcs-filesystem
    Found existing installation: tensorflow-io-gcs-filesystem 0.31.0
    Uninstalling tensorflow-io-gcs-filesystem-0.31.0:
      Successfully uninstalled tensorflow-io-gcs-filesystem-0.31.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.11.0
    Uninstalling tensorflow-estimator-2.11.0:
      Successfully uninstalled tensorflow-estimator-2.11.0
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.6.1
    Uninstalling tensorboard-data-server-0.6.1:
      Successfully uninstalled tensorboard-data-server-0.6.1
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12

**Comment by Rubiksman78** [comment]
The update seems to have only pulled the one from last week and not the last to date, try pulling manually or resintall from the drive link.
