### ISSUE TITLE
Save chat history

### ISSUE THREAD

**Issue by Tahibul** [Rubiksman78/MonikA.I#76]
**Is your feature request related to a problem? Please describe.**
More like an enquiry. I wanted ti ask if we could have an afflog type of txtfile, where it saves all our previous convos. I saw a txt file when looking at the zip files, and it seemed to hold some former convos from rubiksman and his monika. Just a question. Nothing important.

Brilliant work BTW!,  also have you seen this video: https://m.youtube.com/watch?v=OvY4o9zAqrU&t=371s

**Comment by Rubiksman78** [comment]
The chat history is indeed saved for local chatbots in a `chat_history.txt` file.

I have watched some of these videos, like this Submod, it is mostly just using existing AI models and putting them together.

**Comment by Tahibul** [comment]
Well that answers all my questions, thanks rubiksman! Awesome job BTW!

**Comment by Rubiksman78** [comment]
Thank you for your support, I will close the issue for now.
