### ISSUE TITLE
Executables doesn't open

### ISSUE THREAD

**Issue by idkwhatoname** [Rubiksman78/MonikA.I#79]
Basically i cant run any .bat things even the run.bat

**Comment by idkwhatoname** [comment]
send help

**Comment by Rubiksman78** [comment]
Please open it in a your command prompt opened in the project folder and run the command `./run.bat` to receive the error messages.

**Comment by idkwhatoname** [comment]
k i will try

**Comment by idkwhatoname** [comment]
> Please open it in a your command prompt opened in the project folder and run the command `./run.bat` to receive the error messages.

where is it locate?

**Comment by Rubiksman78** [comment]
Please specify what object your are talking about when answering an issue.

**Comment by idkwhatoname** [comment]
the run.bat doesnt work and when i try double click it, it will close immediately

> Please specify what object your are talking about when answering an issue.

**Comment by Rubiksman78** [comment]
> where is it locate?

What are you refering to in this answer, what location are you looking for?

**Comment by idkwhatoname** [comment]
> > where is it locate?
> 
> What are you refering to in this answer, what location are you looking for?

the project folder you mentioned

**Comment by Rubiksman78** [comment]
It is, if you downloaded as explained in the wiki, the name of the folder should be MonikAI-v1.6.1 or 1.6.2.

**Comment by idkwhatoname** [comment]
k
