### ISSUE TITLE
character-ai open and stuck

### ISSUE THREAD

**Issue by 10882** [Rubiksman78/MonikA.I#80]
Good evening evryone.

Using the latest versions. 

character-ai is used, it reaches this window and nothing else happens. 
the first time after manual authorization everything was fine

![image](https://github.com/Rubiksman78/MonikA.I/assets/62587713/410cde14-17d7-4460-b15c-2ce594dd7454)

In terminal I have this:
![image](https://github.com/Rubiksman78/MonikA.I/assets/62587713/d0811aec-ad8a-4464-a1ea-fec378b9378b)

**Comment by Rubiksman78** [comment]
CAI due to their constant changes in their website is pretty much broken and I don't have the time to update it regularly currently. You can try to rely on local chatbots if you have a GPU.
