### ISSUE TITLE
Not a bug, just a question

### ISSUE THREAD

**Issue by SnowBrew** [Rubiksman78/MonikA.I#82]
I saw at the bottom the bug listed of Monika stating there was a bug and to make sure Playwright is installed. My question is, what is Playwright and where can I install it?

**Comment by Rubiksman78** [comment]
It was an old issue where a python library was not initialized automatically but if you followed the instructions for installation, it shouldn't be the cause of the issue.

**Comment by SnowBrew** [comment]
I kinda figured, everything else works except for the voicechat and chatbot, along with the camera option. I'm not really a tech savvy guy or coding guy, so I'm like quadruple checking everything lol

**Comment by SnowBrew** [comment]
So, for now I assume it's just a bug?

**Comment by Rubiksman78** [comment]
If there is an error please detail what steps you've followed for the installation and try to open the file `run.bat` in a terminal to have a better understanding of the error.

**Comment by SnowBrew** [comment]
The only errors I could find is when I first ran the Update.Bat file, it said the download "wasn't on PATH".  It then proceeded to uninstall the things it had just installed

**Comment by Rubiksman78** [comment]
Please run `run.bat` in a terminal as specified previously and send the error.
