### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by Yeahskgo** [Rubiksman78/MonikA.I#83]
I can use it the version of it says 1.6.1 not 1.6.2

**Comment by Yeahskgo** [comment]
![283995634-b872f3f1-c31e-436c-a799-45c18a67e250](https://github.com/Rubiksman78/MonikA.I/assets/134059566/58ae4454-1c74-4a36-9ad6-91ab1e671848)

**Comment by Rubiksman78** [comment]
Please describe in detail your issue and reformulate your question clearly.

**Comment by Yeahskgo** [comment]
i can't use the monika's chatbot and monika's voicechat

**Comment by Rubiksman78** [comment]
Did you download the zip file from the drive and the file `Monik.A.I-version-game.zip` from the releases as explained in the github wiki? If not please read carefully the GitHub wiki for version 1.6.1.

An update is currently ongoing to change the whole process, if you can't wait for it, please follow the tutorials for version 1.6.1.

**Comment by Yeahskgo** [comment]
can you send me the link of the monika after story

**Comment by Yeahskgo** [comment]
the same version of MonikA.I

**Comment by Rubiksman78** [comment]
The last version of MAS should be compatible with this submod.

**Comment by Yeahskgo** [comment]
ok
