### ISSUE TITLE
the mod take so much RAM

### ISSUE THREAD

**Issue by Al666v** [Rubiksman78/MonikA.I#96]
Is this normal? Everytime i run the chatbot it always take all of my memory. It's so laggy.

My Ram; 12GB,
Intel i31005G1
Intel UHD

**Comment by Rubiksman78** [comment]
If you don't have a GPU and a very low end CPU, it is too be expected that RAM usage will be high for chatbot causing a lot of latency. If you can provide information about which model you are currently using, it might explain it.

**Comment by Al666v** [comment]
I'm using Acer Aspire 5 5 a514-53g.

**Comment by Rubiksman78** [comment]
I was asking about which chatbot model you were using.

**Comment by Al666v** [comment]
ohh, it's the one on your tutorial. Is it actually because of the model?

**Comment by Rubiksman78** [comment]
Bigger model also means higher computation ressources usage, but small models are also really bad in terms of quality.

**Comment by Al666v** [comment]
Do you have recommendation in mind for low end though?

**Comment by Rubiksman78** [comment]
Maybe you can try GGUF models with quantized versions that should be lighter with reasonable performance. However, no GPU and an i3 CPU will clearly restrict your usage with high latency even with a smaller model.

**Comment by Al666v** [comment]
I need yo upgrade my gear, really. Anyway Thanks!
